name: CI Checks

on:
  workflow_call:
  pull_request:
    branches: [main]

jobs:
  checks:
    strategy:
      fail-fast: true
      matrix:
        node-version: [18, 24, 26]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - node-version: 18
            os: windows-latest
          - node-version: 18
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build frontend
        run: yarn build
