name: Deploy Template

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Имя Docker-образа (без юзернейма, например: devops-backend)'
        required: true
        type: string
      deploy_dir:
        description: 'Путь к директории проекта на сервере'
        required: true
        type: string
      compose_service:
        description: 'Имя сервиса в docker-compose.yml'
        required: true
        type: string
      env_image_var:
        description: 'Переменная окружения для замены в .env файле'
        required: true
        type: string
    secrets:
      DOCKER_USER:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1
        env:
          # Формируем целевой образ, опираясь на параметры и глобальный хэш коммита
          TARGET_IMAGE: ${{ secrets.DOCKER_USER }}/${{ inputs.image_name }}:sha-${{ github.sha }}
          ENV_VAR_NAME: ${{ inputs.env_image_var }}
          DEPLOY_DIR: ${{ inputs.deploy_dir }}
          COMPOSE_SERVICE: ${{ inputs.compose_service }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: TARGET_IMAGE, ENV_VAR_NAME, DEPLOY_DIR, COMPOSE_SERVICE
          script: |
            cd $DEPLOY_DIR
            
            # Обновляем тег образа в .env файле
            sed -i "s|^${ENV_VAR_NAME}=.*|${ENV_VAR_NAME}=${TARGET_IMAGE}|" .env
            
            # Перезапускаем только обновленный сервис
            docker compose up -d --no-deps $COMPOSE_SERVICE