name: Notify Template

on:
  workflow_call:
    inputs:
      checks_result:
        type: string
        required: true
      build_result:
        type: string
        required: true
      deploy_result:
        type: string
        required: true
    secrets:
      TELEGRAM_BOT_TOKEN:
        required: true
      TELEGRAM_CHAT_ID:
        required: true

jobs:
  notify-tg:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CHECKS: ${{ inputs.checks_result }}
          BUILD: ${{ inputs.build_result }}
          DEPLOY: ${{ inputs.deploy_result }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
          URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          if [ "$CHECKS" != "success" ]; then
            TEXT="❌ <b>Тесты упали</b>%0AПроект: $REPO @ $BRANCH%0A<a href=\"$URL\">Смотреть логи</a>"
          elif [ "$BUILD" != "success" ]; then
            TEXT="❌ <b>Сборка упала</b>%0AПроект: $REPO @ $BRANCH%0A<a href=\"$URL\">Смотреть логи</a>"
          elif [ "$DEPLOY" != "success" ]; then
            TEXT="❌ <b>Деплой упал</b>%0AПроект: $REPO @ $BRANCH%0A<a href=\"$URL\">Смотреть логи</a>"
          else
            TEXT="✅ <b>Деплой успешен</b>%0AПроект: $REPO @ $BRANCH%0AАвтор: $ACTOR"
          fi

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d "chat_id=$TELEGRAM_CHAT_ID" \
            -d "parse_mode=HTML" \
            -d "disable_web_page_preview=true" \
            -d "text=$TEXT"